DataBundle\Entity\AsignacionProducto:
    type: entity
    table: asignacion_producto
    indexes:
        FK_PED_ASIPRO:
            columns:
                - PED_ID
    id:
        asiproId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ASIPRO_ID
            generator:
                strategy: IDENTITY
    fields:
        asiproObservacion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: ASIPRO_OBSERVACION
    manyToOne:
        ped:
            targetEntity: Pedido
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PED_ID:
                    referencedColumnName: PED_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
