DataBundle\Entity\BancoCliente:
    type: entity
    table: banco_cliente
    indexes:
        FK_BAN_BANCLI:
            columns:
                - BAN_ID
        FK_CLI_BANCLI:
            columns:
                - CLI_ID
    id:
        bancliId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: BANCLI_ID
            generator:
                strategy: IDENTITY
    fields:
        bancliDescripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: BANCLI_DESCRIPCION
    manyToOne:
        ban:
            targetEntity: Banco
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                BAN_ID:
                    referencedColumnName: BAN_ID
            orphanRemoval: false
        cli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CLI_ID:
                    referencedColumnName: CLI_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
