DataBundle\Entity\CajaCierre:
    type: entity
    table: caja_cierre
    indexes:
        FK_CAJ_CAJCIE:
            columns:
                - CAJ_ID
        FK_COM_CAJCIE:
            columns:
                - COM_ID
        FK_VEN_CAJCIE:
            columns:
                - VEN_ID
    id:
        cierId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CIER_ID
            generator:
                strategy: IDENTITY
    fields:
        cierFecha:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CIER_FECHA
        cierTotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CIER_TOTAL
    manyToOne:
        caj:
            targetEntity: Caja
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CAJ_ID:
                    referencedColumnName: CAJ_ID
            orphanRemoval: false
        com:
            targetEntity: Compra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                COM_ID:
                    referencedColumnName: COM_ID
            orphanRemoval: false
        ven:
            targetEntity: Venta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                VEN_ID:
                    referencedColumnName: VEN_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
