DataBundle\Entity\Cheque:
    type: entity
    table: cheque
    indexes:
        FK_CUE_CHE:
            columns:
                - CUE_ID
        FK_TIPCHE_CHE:
            columns:
                - TIPCHE_ID
    id:
        cheId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CHE_ID
            generator:
                strategy: IDENTITY
    fields:
        cheNumerocheque:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
            column: CHE_NUMEROCHEQUE
        cheValor:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CHE_VALOR
        cheFechapago:
            type: date
            nullable: true
            column: CHE_FECHAPAGO
    manyToOne:
        cue:
            targetEntity: Cuenta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CUE_ID:
                    referencedColumnName: CUE_ID
            orphanRemoval: false
        tipche:
            targetEntity: TipoCheque
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                TIPCHE_ID:
                    referencedColumnName: TIPCHE_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
