DataBundle\Entity\ClienteCategoria:
    type: entity
    table: cliente_categoria
    id:
        clicatId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CLICAT_ID
            generator:
                strategy: IDENTITY
    fields:
        clicatCantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CLICAT_CANTIDAD
    lifecycleCallbacks: {  }
