DataBundle\Entity\Consignacion:
    type: entity
    table: consignacion
    indexes:
        FK_CLI_CON:
            columns:
                - CLI_ID
        FK_LOCSUC_CON:
            columns:
                - LOC_ID
    id:
        conId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CON_ID
            generator:
                strategy: IDENTITY
    fields:
        conNumero:
            type: string
            nullable: true
            length: 9
            options:
                fixed: true
            column: CON_NUMERO
        conSubtotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CON_SUBTOTAL
        conIva:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CON_IVA
        conValoriva:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CON_VALORIVA
        conValoriva0:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CON_VALORIVA0
        conIce:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CON_ICE
        conValorice:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CON_VALORICE
        conDescuento:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CON_DESCUENTO
        conTotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: CON_TOTAL
        conFechaemision:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: CON_FECHAEMISION
        conNumeroproducto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CON_NUMEROPRODUCTO
        conEstado:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: CON_ESTADO
        conSerie:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: CON_SERIE
    manyToOne:
        cli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CLI_ID:
                    referencedColumnName: CLI_ID
            orphanRemoval: false
        loc:
            targetEntity: LocalSucursal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                LOC_ID:
                    referencedColumnName: LOC_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
