DataBundle\Entity\DetalleConsignacion:
    type: entity
    table: detalle_consignacion
    indexes:
        FK_CON_DETCON:
            columns:
                - CON_ID
        FK_PRO_DETCON:
            columns:
                - PRO_ID2
    id:
        detconId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETCON_ID
            generator:
                strategy: IDENTITY
    fields:
        detconCantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCON_CANTIDAD
        detconValorunitario:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETCON_VALORUNITARIO
        detconValortotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETCON_VALORTOTAL
    manyToOne:
        con:
            targetEntity: Consignacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CON_ID:
                    referencedColumnName: CON_ID
            orphanRemoval: false
        pro2:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRO_ID2:
                    referencedColumnName: PRO_ID2
            orphanRemoval: false
    lifecycleCallbacks: {  }
