DataBundle\Entity\DetalleVenta:
    type: entity
    table: detalle_venta
    indexes:
        FK_FACVEN_DETVEN:
            columns:
                - FACVEN_ID
        FK_PRO_DETVEN:
            columns:
                - PRO_ID2
    id:
        detvenId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETVEN_ID
            generator:
                strategy: IDENTITY
    fields:
        detvenCantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETVEN_CANTIDAD
        detvenValorunitario:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETVEN_VALORUNITARIO
        detvenValortotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETVEN_VALORTOTAL
    manyToOne:
        facven:
            targetEntity: FacturaVenta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FACVEN_ID:
                    referencedColumnName: FACVEN_ID
            orphanRemoval: false
        pro2:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRO_ID2:
                    referencedColumnName: PRO_ID2
            orphanRemoval: false
    lifecycleCallbacks: {  }
