DataBundle\Entity\DetallePedido:
    type: entity
    table: detalle_pedido
    indexes:
        FK_PER_DETPED:
            columns:
                - PED_ID
        FK_PRO_DETPED:
            columns:
                - PRO_ID2
    id:
        detpedId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETPED_ID
            generator:
                strategy: IDENTITY
    fields:
        detpedCantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETPED_CANTIDAD
    manyToOne:
        ped:
            targetEntity: Pedido
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PED_ID:
                    referencedColumnName: PED_ID
            orphanRemoval: false
        pro2:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRO_ID2:
                    referencedColumnName: PRO_ID2
            orphanRemoval: false
    lifecycleCallbacks: {  }
