DataBundle\Entity\DetalleBaja:
    type: entity
    table: detalle_baja
    indexes:
        FK_BAJ_DETBAJ:
            columns:
                - BAJ_ID
        FK_PRO_DETBAJ:
            columns:
                - PRO_ID2
    id:
        detbajId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETBAJ_ID
            generator:
                strategy: IDENTITY
    fields:
        detbajCantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETBAJ_CANTIDAD
        detbajMotivos:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: DETBAJ_MOTIVOS
    manyToOne:
        baj:
            targetEntity: Baja
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                BAJ_ID:
                    referencedColumnName: BAJ_ID
            orphanRemoval: false
        pro2:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRO_ID2:
                    referencedColumnName: PRO_ID2
            orphanRemoval: false
    lifecycleCallbacks: {  }
