DataBundle\Entity\DetalleCompra:
    type: entity
    table: detalle_compra
    indexes:
        FK_FACCOM_DETCOM:
            columns:
                - FACCOM_ID
        FK_PRO_DETCOM:
            columns:
                - PRO_ID2
    id:
        detcomId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETCOM_ID
        proId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PRO_ID
    fields:
        detcomCantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCOM_CANTIDAD
        detcomCostounitario:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETCOM_COSTOUNITARIO
        detcomCostototal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETCOM_COSTOTOTAL
    manyToOne:
        faccom:
            targetEntity: FacturaCompra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FACCOM_ID:
                    referencedColumnName: FACCOM_ID
            orphanRemoval: false
        pro2:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRO_ID2:
                    referencedColumnName: PRO_ID2
            orphanRemoval: false
    lifecycleCallbacks: {  }
