DataBundle\Entity\DetalleIngreso:
    type: entity
    table: detalle_ingreso
    indexes:
        FK_VEN_DETING:
            columns:
                - VEN_ID
    id:
        detingId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETING_ID
            generator:
                strategy: IDENTITY
    manyToOne:
        ven:
            targetEntity: Venta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                VEN_ID:
                    referencedColumnName: VEN_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
