DataBundle\Entity\DetalleMovilizacionIngreso:
    type: entity
    table: detalle_movilizacion_ingreso
    indexes:
        FK_MOV_DETMOVING:
            columns:
                - MOV_ID
        FK_PRO_DETMOVING:
            columns:
                - PRO_ID2
    id:
        detmoviId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETMOVI_ID
            generator:
                strategy: IDENTITY
    manyToOne:
        mov:
            targetEntity: Movilizacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                MOV_ID:
                    referencedColumnName: MOV_ID
            orphanRemoval: false
        pro2:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRO_ID2:
                    referencedColumnName: PRO_ID2
            orphanRemoval: false
    lifecycleCallbacks: {  }
