DataBundle\Entity\DetalleCajaCierre:
    type: entity
    table: detalle_caja_cierre
    indexes:
        FK_CAJCIE_DETCAJCIE:
            columns:
                - CIER_ID
    id:
        detcieId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETCIE_ID
            generator:
                strategy: IDENTITY
    fields:
        detcieFecha:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: DETCIE_FECHA
        detcie1cent:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_1CENT
        detcie5cent:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_5CENT
        detcie10cent:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_10CENT
        detcie25cent:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_25CENT
        detcie50cent:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_50CENT
        detcie1dol:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_1DOL
        detcie2dol:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_2DOL
        detcie5dol:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_5DOL
        detcie10dol:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_10DOL
        detcie20dol:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_20DOL
        detcie50dol:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_50DOL
        detcie100dol:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETCIE_100DOL
        detcieTotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETCIE_TOTAL
    manyToOne:
        cier:
            targetEntity: CajaCierre
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CIER_ID:
                    referencedColumnName: CIER_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
