DataBundle\Entity\Efectivo:
    type: entity
    table: efectivo
    id:
        efeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: EFE_ID
            generator:
                strategy: IDENTITY
    fields:
        efeValor:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: EFE_VALOR
    lifecycleCallbacks: {  }
