DataBundle\Entity\Empleado:
    type: entity
    table: empleado
    id:
        empId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: EMP_ID
            generator:
                strategy: IDENTITY
    fields:
        empNombre:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: EMP_NOMBRE
        empApellido:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: EMP_APELLIDO
        empDireccion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: EMP_DIRECCION
        empTelefono1:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: EMP_TELEFONO1
        empTelefono2:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: EMP_TELEFONO2
        empTiposangre:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: EMP_TIPOSANGRE
        empCorreo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: EMP_CORREO
        empAvisaremergencia:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: EMP_AVISAREMERGENCIA
        empTelefonoemergencia:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: EMP_TELEFONOEMERGENCIA
        empParentezcoemergencia:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: EMP_PARENTEZCOEMERGENCIA
        empDescripcionalergias:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: EMP_DESCRIPCIONALERGIAS
        empDescripciongeneral:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: EMP_DESCRIPCIONGENERAL
        empEstado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: EMP_ESTADO
        empFechanacimiento:
            type: date
            nullable: true
            column: EMP_FECHANACIMIENTO
        empIdentificacion:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
            column: EMP_IDENTIFICACION
    lifecycleCallbacks: {  }
