DataBundle\Entity\FacturaCompra:
    type: entity
    table: factura_compra
    indexes:
        FK_EMPPRO_FACCOM:
            columns:
                - EMPPRO_ID
        FK_FORPAG_FACCOM:
            columns:
                - FORPAG_ID
        FK_LOCSUC_FACCOM:
            columns:
                - LOC_ID
    id:
        faccomId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: FACCOM_ID
            generator:
                strategy: IDENTITY
    fields:
        faccomNumerofactura:
            type: string
            nullable: true
            length: 9
            options:
                fixed: true
            column: FACCOM_NUMEROFACTURA
        faccomSubtotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_SUBTOTAL
        faccomIva:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_IVA
        faccomValoriva:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_VALORIVA
        faccomValoriva0:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_VALORIVA0
        faccomIce:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_ICE
        faccomValorice:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_VALORICE
        faccomDescuento:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_DESCUENTO
        faccomTotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: FACCOM_TOTAL
        faccomFecha:
            type: date
            nullable: true
            column: FACCOM_FECHA
        faccomNumeroproductos:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FACCOM_NUMEROPRODUCTOS
        faccomEstado:
            type: string
            nullable: true
            length: 3
            options:
                fixed: true
            column: FACCOM_ESTADO
        faccomSerie:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
            column: FACCOM_SERIE
        faccomTipodoc:
            type: string
            nullable: true
            length: 3
            options:
                fixed: true
            column: FACCOM_TIPODOC
    manyToOne:
        emppro:
            targetEntity: EmpresaProveedora
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                EMPPRO_ID:
                    referencedColumnName: EMPPRO_ID
            orphanRemoval: false
        forpag:
            targetEntity: FormaPago
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FORPAG_ID:
                    referencedColumnName: FORPAG_ID
            orphanRemoval: false
        loc:
            targetEntity: LocalSucursal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                LOC_ID:
                    referencedColumnName: LOC_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
