DataBundle\Entity\ProductoExtra:
    type: entity
    table: producto_extra
    id:
        proextId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PROEXT_ID
            generator:
                strategy: IDENTITY
    fields:
        proextNombre:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: PROEXT_NOMBRE
        proextDescripcion:
            type: string
            nullable: true
            length: 70
            options:
                fixed: false
            column: PROEXT_DESCRIPCION
        proextTipo:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: PROEXT_TIPO
    lifecycleCallbacks: {  }
