DataBundle\Entity\Provincia:
    type: entity
    table: provincia
    id:
        provId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PROV_ID
            generator:
                strategy: IDENTITY
    fields:
        provNombre:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: PROV_NOMBRE
        provRegion:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: PROV_REGION
    lifecycleCallbacks: {  }
