DataBundle\Entity\Sesion:
    type: entity
    table: sesion
    indexes:
        FK_EMPLOC_SES:
            columns:
                - EMPLOC_ID
    id:
        sesId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: SES_ID
            generator:
                strategy: IDENTITY
    fields:
        sesFechaingreso:
            type: date
            nullable: true
            column: SES_FECHAINGRESO
        sesNumintento:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SES_NUMINTENTO
        sesHoraingreso:
            type: time
            nullable: true
            column: SES_HORAINGRESO
        sesDescripcioningreso:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: SES_DESCRIPCIONINGRESO
    manyToOne:
        emploc:
            targetEntity: EmpleadoLocal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                EMPLOC_ID:
                    referencedColumnName: EMPLOC_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
