DataBundle\Entity\TipoCheque:
    type: entity
    table: tipo_cheque
    id:
        tipcheId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: TIPCHE_ID
            generator:
                strategy: IDENTITY
    fields:
        tipcheNombre:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: TIPCHE_NOMBRE
    lifecycleCallbacks: {  }
