DataBundle\Entity\Vehiculo:
    type: entity
    table: vehiculo
    id:
        vehId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: VEH_ID
            generator:
                strategy: IDENTITY
    fields:
        vehTipo:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: VEH_TIPO
        vehModelo:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: VEH_MODELO
        vehCilindraje:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: VEH_CILINDRAJE
        vehTonelaje:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: VEH_TONELAJE
    lifecycleCallbacks: {  }
