BackBundle\Entity\Cargo:
    type: entity
    table: cargo
    id:
        carId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CAR_ID
            generator:
                strategy: IDENTITY
    fields:
        carNombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CAR_NOMBRE
        carDescripcion:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CAR_DESCRIPCION
    lifecycleCallbacks: {  }
