BackBundle\Entity\Compra:
    type: entity
    table: compra
    id:
        comId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: COM_ID
            generator:
                strategy: IDENTITY
    fields:
        comFecha:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: COM_FECHA
        comTotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: COM_TOTAL
    lifecycleCallbacks: {  }
