BackBundle\Entity\Cotizacion:
    type: entity
    table: cotizacion
    indexes:
        FK_CLI_COT:
            columns:
                - CLI_ID
        FK_LOCSUC_COT:
            columns:
                - LOC_ID
    id:
        cotId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: COT_ID
            generator:
                strategy: IDENTITY
    fields:
        cotNumerocotizacion:
            type: string
            nullable: true
            length: 9
            options:
                fixed: true
            column: COT_NUMEROCOTIZACION
        cotSubtotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: COT_SUBTOTAL
        cotIva:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: COT_IVA
        cotValoriva:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: COT_VALORIVA
        cotValoriva0:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: COT_VALORIVA0
        cotIce:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: COT_ICE
        cotValorice:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: COT_VALORICE
        cotDescuento:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: COT_DESCUENTO
        cotTotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: COT_TOTAL
        cotFechaemision:
            type: date
            nullable: true
            column: COT_FECHAEMISION
        cotFechavalidez:
            type: date
            nullable: true
            column: COT_FECHAVALIDEZ
        cotNumeroproducto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: COT_NUMEROPRODUCTO
        cotEstado:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: COT_ESTADO
        cotSerie:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: COT_SERIE
    manyToOne:
        cli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CLI_ID:
                    referencedColumnName: CLI_ID
            orphanRemoval: false
        loc:
            targetEntity: LocalSucursal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                LOC_ID:
                    referencedColumnName: LOC_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
