BackBundle\Entity\DetalleGasto:
    type: entity
    table: detalle_gasto
    indexes:
        FK_GAS_DETGAS:
            columns:
                - GAS_ID
        FK_PROEXT_DETGAS:
            columns:
                - PROEXT_ID
    id:
        detgasId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: DETGAS_ID
            generator:
                strategy: IDENTITY
    fields:
        detgasCantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DETGAS_CANTIDAD
        detgasValorunitario:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETGAS_VALORUNITARIO
        detgasValortotal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: DETGAS_VALORTOTAL
    manyToOne:
        gas:
            targetEntity: Gasto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                GAS_ID:
                    referencedColumnName: GAS_ID
            orphanRemoval: false
        proext:
            targetEntity: ProductoExtra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PROEXT_ID:
                    referencedColumnName: PROEXT_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
