BackBundle\Entity\InventarioLocal:
    type: entity
    table: inventario_local
    indexes:
        FK_DETASI_INVLOC:
            columns:
                - DETASI_ID
        FK_DETBAJ_INVLOC:
            columns:
                - DETBAJ_ID
        FK_DETCOM_INVLOC:
            columns:
                - DETCOM_ID
                - PRO_ID
        FK_DETCON_INVLOC:
            columns:
                - DETCON_ID
        FK_DETDEV_INVLOC:
            columns:
                - DETDEV_ID
        FK_DETMOVING_INVLOC:
            columns:
                - DETMOVI_ID
        FK_DETMOVSAL_INVLOC:
            columns:
                - DETMOVS_ID
        FK_DETVEN_INVLOC:
            columns:
                - DETVEN_ID
        FK_LOCSUC_INVLOC:
            columns:
                - LOC_ID
        FK_PRO_INVLOC:
            columns:
                - PRO_ID2
    id:
        invlocId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: INVLOC_ID
            generator:
                strategy: IDENTITY
    fields:
        invlocCantidadmovimiento:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: INVLOC_CANTIDADMOVIMIENTO
        invlocTipomovimiento:
            type: string
            nullable: true
            length: 2
            options:
                fixed: true
            column: INVLOC_TIPOMOVIMIENTO
        invlocStockreales:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: INVLOC_STOCKREALES
        invlocStocksinconsignacion:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: INVLOC_STOCKSINCONSIGNACION
        invlocFecharegistro:
            type: date
            nullable: true
            column: INVLOC_FECHAREGISTRO
        invlocCostounitario:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: INVLOC_COSTOUNITARIO
        invlocCostototal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: INVLOC_COSTOTOTAL
        invlocPvpsugerido:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: INVLOC_PVPSUGERIDO
        invlocLocalorigen:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: INVLOC_LOCALORIGEN
        invlocLocaldestino:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: INVLOC_LOCALDESTINO
    manyToOne:
        detasi:
            targetEntity: DetalleAsignacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETASI_ID:
                    referencedColumnName: DETASI_ID
            orphanRemoval: false
        detbaj:
            targetEntity: DetalleBaja
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETBAJ_ID:
                    referencedColumnName: DETBAJ_ID
            orphanRemoval: false
        detcom:
            targetEntity: DetalleCompra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETCOM_ID:
                    referencedColumnName: DETCOM_ID
                PRO_ID:
                    referencedColumnName: PRO_ID
            orphanRemoval: false
        detcon:
            targetEntity: DetalleConsignacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETCON_ID:
                    referencedColumnName: DETCON_ID
            orphanRemoval: false
        detdev:
            targetEntity: DetalleDevolucion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETDEV_ID:
                    referencedColumnName: DETDEV_ID
            orphanRemoval: false
        detmovi:
            targetEntity: DetalleMovilizacionIngreso
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETMOVI_ID:
                    referencedColumnName: DETMOVI_ID
            orphanRemoval: false
        detmovs:
            targetEntity: DetalleMovilizacionSalida
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETMOVS_ID:
                    referencedColumnName: DETMOVS_ID
            orphanRemoval: false
        detven:
            targetEntity: DetalleVenta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                DETVEN_ID:
                    referencedColumnName: DETVEN_ID
            orphanRemoval: false
        loc:
            targetEntity: LocalSucursal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                LOC_ID:
                    referencedColumnName: LOC_ID
            orphanRemoval: false
        pro2:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRO_ID2:
                    referencedColumnName: PRO_ID2
            orphanRemoval: false
    lifecycleCallbacks: {  }
