BackBundle\Entity\Localidad:
    type: entity
    table: localidad
    indexes:
        FK_PROV_LOC:
            columns:
                - PROV_ID
    id:
        locaId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: LOCA_ID
            generator:
                strategy: IDENTITY
    fields:
        locaNombre:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: LOCA_NOMBRE
    manyToOne:
        prov:
            targetEntity: Provincia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PROV_ID:
                    referencedColumnName: PROV_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
