BackBundle\Entity\LocalSucursal:
    type: entity
    table: local_sucursal
    indexes:
        FK_ALM_LOCSUC:
            columns:
                - ALM_ID
        FK_GEO_LOCSUC:
            columns:
                - GEO_ID
        FK_PARLOC_LOCSUC:
            columns:
                - PARLOC_ID
    id:
        locId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: LOC_ID
            generator:
                strategy: IDENTITY
    fields:
        locNombre:
            type: string
            nullable: true
            length: 60
            options:
                fixed: true
            column: LOC_NOMBRE
        locDireccion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: LOC_DIRECCION
        locEstado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: LOC_ESTADO
        locFax:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: LOC_FAX
        locTelefono1:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: LOC_TELEFONO1
        locTelefono2:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: LOC_TELEFONO2
        locDescripcion:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LOC_DESCRIPCION
        locCodigo:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: LOC_CODIGO
        locFechainaguracion:
            type: date
            nullable: true
            column: LOC_FECHAINAGURACION
        locFechacierre:
            type: date
            nullable: true
            column: LOC_FECHACIERRE
        locMatrizOSucursal:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: LOC_MATRIZ_O_SUCURSAL
        locRuc:
            type: string
            nullable: true
            length: 13
            options:
                fixed: true
            column: LOC_RUC
        locMail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LOC_MAIL
    manyToOne:
        alm:
            targetEntity: Almacen
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ALM_ID:
                    referencedColumnName: ALM_ID
            orphanRemoval: false
        geo:
            targetEntity: Georeferencia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                GEO_ID:
                    referencedColumnName: GEO_ID
            orphanRemoval: false
        parloc:
            targetEntity: ParametroLocal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PARLOC_ID:
                    referencedColumnName: PARLOC_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
