BackBundle\Entity\ModuloSistema:
    type: entity
    table: modulo_sistema
    id:
        modsisId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: MODSIS_ID
            generator:
                strategy: IDENTITY
    fields:
        modsisNombre:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: MODSIS_NOMBRE
        modsisPadre:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: MODSIS_PADRE
        modsisUbicacion:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: MODSIS_UBICACION
        modsisEstado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: MODSIS_ESTADO
        modsisNombremostrar:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: MODSIS_NOMBREMOSTRAR
    lifecycleCallbacks: {  }
