BackBundle\Entity\Parametro:
    type: entity
    table: parametro
    id:
        parId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PAR_ID
            generator:
                strategy: IDENTITY
    fields:
        parNombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: PAR_NOMBRE
        parTipo:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: PAR_TIPO
        parFecharegistro:
            type: date
            nullable: true
            column: PAR_FECHAREGISTRO
        parEstadoactivo:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: PAR_ESTADOACTIVO
    lifecycleCallbacks: {  }
