BackBundle\Entity\Producto:
    type: entity
    table: producto
    id:
        proId2:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PRO_ID2
            generator:
                strategy: IDENTITY
    fields:
        proCodigo:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
            column: PRO_CODIGO
        proFecharegistro:
            type: date
            nullable: true
            column: PRO_FECHAREGISTRO
        proEstado:
            type: string
            nullable: true
            length: 13
            options:
                fixed: true
            column: PRO_ESTADO
        proNombre:
            type: string
            nullable: true
            length: 50
            options:
                fixed: true
            column: PRO_NOMBRE
        proContenido:
            type: string
            nullable: true
            length: 10
            options:
                fixed: true
            column: PRO_CONTENIDO
        proDescripcion:
            type: string
            nullable: true
            length: 100
            options:
                fixed: true
            column: PRO_DESCRIPCION
        proTipouso:
            type: string
            nullable: true
            length: 10
            options:
                fixed: true
            column: PRO_TIPOUSO
        proGravaiva:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: PRO_GRAVAIVA
        proGravaice:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: PRO_GRAVAICE
        proFechaelaboracion:
            type: date
            nullable: true
            column: PRO_FECHAELABORACION
        proFechacaducidad:
            type: date
            nullable: true
            column: PRO_FECHACADUCIDAD
        proCodigoprov:
            type: string
            nullable: true
            length: 30
            options:
                fixed: true
            column: PRO_CODIGOPROV
        proTipo:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: PRO_TIPO
    lifecycleCallbacks: {  }
